# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/m_rah/Desktop/assignments/assignment_1/selection_sort_IP/selection_sort_IP.srcs/sources_1/bd/selection_sort_IP/ip/selection_sort_IP_processing_system7_0_0/selection_sort_IP_processing_system7_0_0.xci
# IP: The module: 'selection_sort_IP_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/m_rah/Desktop/assignments/assignment_1/selection_sort_IP/selection_sort_IP.srcs/sources_1/bd/selection_sort_IP/ip/selection_sort_IP_processing_system7_0_0/selection_sort_IP_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'selection_sort_IP_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/m_rah/Desktop/assignments/assignment_1/selection_sort_IP/selection_sort_IP.srcs/sources_1/bd/selection_sort_IP/ip/selection_sort_IP_processing_system7_0_0/selection_sort_IP_processing_system7_0_0.xci
# IP: The module: 'selection_sort_IP_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/m_rah/Desktop/assignments/assignment_1/selection_sort_IP/selection_sort_IP.srcs/sources_1/bd/selection_sort_IP/ip/selection_sort_IP_processing_system7_0_0/selection_sort_IP_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'selection_sort_IP_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
