# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/selection_sort_IP/selection_sort_IP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_IP || ORIG_REF_NAME==selection_sort_IP} -quiet] -quiet

# IP: bd/selection_sort_IP/ip/selection_sort_IP_processing_system7_0_0/selection_sort_IP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_IP_processing_system7_0_0 || ORIG_REF_NAME==selection_sort_IP_processing_system7_0_0} -quiet] -quiet

# IP: bd/selection_sort_IP/ip/selection_sort_IP_selection_sort_IP_0_0/selection_sort_IP_selection_sort_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_IP_selection_sort_IP_0_0 || ORIG_REF_NAME==selection_sort_IP_selection_sort_IP_0_0} -quiet] -quiet

# IP: bd/selection_sort_IP/ip/selection_sort_IP_auto_pc_0/selection_sort_IP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_IP_auto_pc_0 || ORIG_REF_NAME==selection_sort_IP_auto_pc_0} -quiet] -quiet

# IP: bd/selection_sort_IP/ip/selection_sort_IP_ps7_0_axi_periph_0/selection_sort_IP_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_IP_ps7_0_axi_periph_0 || ORIG_REF_NAME==selection_sort_IP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/selection_sort_IP/ip/selection_sort_IP_rst_ps7_0_100M_0/selection_sort_IP_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_IP_rst_ps7_0_100M_0 || ORIG_REF_NAME==selection_sort_IP_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/selection_sort_IP/selection_sort_IP_ooc.xdc
