# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/selection_sort_design/selection_sort_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design || ORIG_REF_NAME==selection_sort_design} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_processing_system7_0_0/selection_sort_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_processing_system7_0_0 || ORIG_REF_NAME==selection_sort_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_selection_sort_0_0/selection_sort_design_selection_sort_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_selection_sort_0_0 || ORIG_REF_NAME==selection_sort_design_selection_sort_0_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_ps7_0_axi_periph_0/selection_sort_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==selection_sort_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_rst_ps7_0_100M_0/selection_sort_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==selection_sort_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_blk_mem_gen_0_0/selection_sort_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_blk_mem_gen_0_0 || ORIG_REF_NAME==selection_sort_design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_blk_mem_gen_0_0_1/selection_sort_design_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_blk_mem_gen_0_0 || ORIG_REF_NAME==selection_sort_design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_xbar_0/selection_sort_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_xbar_0 || ORIG_REF_NAME==selection_sort_design_xbar_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_sort_controller_0_0/selection_sort_design_sort_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_sort_controller_0_0 || ORIG_REF_NAME==selection_sort_design_sort_controller_0_0} -quiet] -quiet

# IP: bd/selection_sort_design/ip/selection_sort_design_auto_pc_0/selection_sort_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==selection_sort_design_auto_pc_0 || ORIG_REF_NAME==selection_sort_design_auto_pc_0} -quiet] -quiet

# XDC: bd/selection_sort_design/ip/selection_sort_design_processing_system7_0_0/selection_sort_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==selection_sort_design_processing_system7_0_0 || ORIG_REF_NAME==selection_sort_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/selection_sort_design/ip/selection_sort_design_rst_ps7_0_100M_0/selection_sort_design_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==selection_sort_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==selection_sort_design_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/selection_sort_design/ip/selection_sort_design_rst_ps7_0_100M_0/selection_sort_design_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==selection_sort_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==selection_sort_design_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/selection_sort_design/ip/selection_sort_design_blk_mem_gen_0_0_1/selection_sort_design_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/selection_sort_design/ip/selection_sort_design_xbar_0/selection_sort_design_xbar_0_ooc.xdc

# XDC: bd/selection_sort_design/ip/selection_sort_design_auto_pc_0/selection_sort_design_auto_pc_0_ooc.xdc

# XDC: bd/selection_sort_design/selection_sort_design_ooc.xdc
